# These labels are heavily based upon those of Skyra repository
# (https://github.com/skyra-project/skyra), all credit goes to them.
#
# The Skyra repository is licensed under the terms of Apache License, see
# <https://github.com/skyra-project/skyra/blob/main/LICENSE> for further
# details.
#
# Copyright 2019-2020 Antonio Román, Apache License.

- name: 'Bug: Already Fixed'
  description: Issues that report already fixed bugs.
  color: B3E88C

- name: 'Bug: Cannot Reproduce'
  description: Issues that report bugs that cannot be reproduced.
  color: f9d0c4

- name: 'Bug: Upstream'
  description: Bugs in dependencies that need to be fixed upstream.
  color: f9d0c4

- name: 'Bug: Confirmed'
  description: Issues that report confirmed bugs.
  color: f9d0c4

- name: 'Bug: Fixed'
  description: Issues that report bugs and have been fixed.
  color: 00fa9a

- name: 'Bug: Unverified'
  description: Issues that report unverified bugs. Pending for inspection.
  color: f9d0c4

- name: 'Meta: Bike-shedding'
  description: Issues and PRs that nitpick.
  color: f9253a

- name: 'Meta: Bugfix'
  description: PRs that fix bugs or issues.
  color: 4cce4a

- name: 'Meta: Cleanup'
  description: Issues and PRs related to code cleanup.
  color: ffff00

- name: 'Meta: Dependencies'
  description: Issues and PRs related to dependencies.
  color: ffff00

- name: 'Meta: Documentation'
  description: Issues and PRs related to documentation.
  color: ffff00

- name: 'Meta: Error Handling'
  description: Issues and PRs related to error handling.
  color: ffff00

- name: 'Meta: Examples'
  description: Issues and PRs related to examples.
  color: ffff00

- name: 'Meta: Feature'
  description: Issues and PRs related to new features.
  color: ffff00

- name: 'Meta: Github'
  description: Issues and PRs related to GitHub.
  color: ffff00

- name: 'Meta: Refactor'
  description: Issues and PRs related to refactoring.
  color: ffff00

- name: 'Meta: Typings'
  description: Issues and PRs related to typings.
  color: ffff00

- name: 'Priority: Critical'
  description: Critical issues that must be fixed (i.e code that consistently crashes).
  color: b60205

- name: 'Priority: High'
  description: High-priority issues that must be fixed.
  color: d93f0b

- name: 'Priority: Low'
  description: Low-priority issues.
  color: 0e8a16

- name: 'Priority: Medium'
  description: Medium-priority issues.
  color: fbca04

- name: 'Status: Blocked'
  description: PRs that are blocked by other issues/PRs.
  color: d81a0d

- name: 'Status: Changes Requested'
  description: PRs that have requested changes.
  color: d93f0b

- name: 'Status: Denied'
  description: Issues or PRs that have been denied by the team.
  color: bc1202

- name: 'Status: Duplicate'
  description: Issues/PRs that are duplicates.
  color: d93f0b

- name: 'Status: Help Wanted'
  description: Issues that need assistance from volunteers or PRs that need help to
    proceed.
  color: 128A0C

- name: 'Status: Invalid'
  description: Issues that will not be fixed or PRs that will not be merged.
  color: 671df0

- name: 'Status: Needs Docs'
  description: PRs that need documentation
  color: d4c5f9

- name: 'Status: Needs Migration'
  description: PRs that need a database migration script.
  color: d93f0b

- name: 'Status: Needs Testing'
  description: PRs that need testing from the author or volunteers.
  color: d93f0b

- name: 'Status: Ready To Merge'
  description: PRs that are ready to merge.
  color: 05F541

- name: 'Status: Review Ready'
  description: PRs that are ready for review.
  color: 05F541

- name: 'Status: Stalled'
  description: Issues and PRs that are being set aside for now for rethinking
  color: fbca04

- name: 'Status: WIP'
  description: Issues and PRs that are still a work in progress.
  color: b60205

- name: 'Type: Consistency'
  description: Issues and PRs related to code consistency.
  color: 1d76db

- name: 'Type: Dependencies'
  description: Pull requests that update a dependency file.
  color: 0025ff

- name: 'Type: Enhancement'
  description: Issues and PRs related to feature enhancement.
  color: 1d76db

- name: 'Type: Maintenance'
  description: Issues and PRs related to the maintenance of a module.
  color: 1d76db

- name: 'Type: Performance'
  description: Issues and PRs related to the performance of the code.
  color: 1d76db

- name: 'Type: Proposal'
  description: Issues that request a new feature or change in interface.
  color: ffffff

- name: 'Type: Question'
  description: Issues that do not belong to the Issue Tracker and should be asked over Discord or Github instead.
  color: cc317c

- name: 'Type: Security'
  description: PRs that address a security vulnerability.
  color: ee0701

- name: 'Type: Typo'
  description: Issues and PRs related to typos in the documentation or code.
  color: c5def5
