name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/package.json') }}

      - name: Install PNPM and dependencies
        uses: pnpm/action-setup@v1.2.1
        with:
          version: latest
          run_install: |
            args: [--frozen-lockfile, --ignore-scripts]

      - name: Run ESLint
        run: pnpm lint

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install PNPM
        uses: pnpm/action-setup@v1.2.1
        with:
          version: latest

      - name: Setup node-canvas dependencies
        run: |
          sudo apt-get install libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev -y &&
          pnpm add --global node-gyp node-pre-gyp

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Copy configuration
        run: |
          pushd src &&
          cp config.example.yml config.yml &&
          popd

      - name: Run unit tests
        run: pnpm test:ci

  build-project:
    name: Compile source code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/package.json') }}

      - name: Install PNPM and dependencies
        uses: pnpm/action-setup@v1.2.1
        with:
          version: latest
          run_install: |
            - args: [--frozen-lockfile, --ignore-scripts]

      - name: Register problem matcher
        run: echo "##[add-matcher].github/problem-matchers/tsc.json"

      - name: Compile TypeScript
        run: pnpm build
